// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_session.proto

package com.yogi.albatross.common.server;

public final class ServerSessionProto {
  private ServerSessionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerSessionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerSession)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string channelId = 2;</code>
     */
    java.lang.String getChannelId();
    /**
     * <code>string channelId = 2;</code>
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    java.util.List<com.yogi.albatross.common.server.MessageProto.Message> 
        getSendNoAcksList();
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    com.yogi.albatross.common.server.MessageProto.Message getSendNoAcks(int index);
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    int getSendNoAcksCount();
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
        getSendNoAcksOrBuilderList();
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getSendNoAcksOrBuilder(
        int index);

    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    java.util.List<com.yogi.albatross.common.server.MessageProto.Message> 
        getWillSendsList();
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    com.yogi.albatross.common.server.MessageProto.Message getWillSends(int index);
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    int getWillSendsCount();
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
        getWillSendsOrBuilderList();
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getWillSendsOrBuilder(
        int index);

    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    java.util.List<com.yogi.albatross.common.server.MessageProto.Message> 
        getRecNoAcksList();
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    com.yogi.albatross.common.server.MessageProto.Message getRecNoAcks(int index);
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    int getRecNoAcksCount();
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
        getRecNoAcksOrBuilderList();
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getRecNoAcksOrBuilder(
        int index);

    /**
     * <code>int64 keepLiveSecond = 6;</code>
     */
    long getKeepLiveSecond();

    /**
     * <code>int32 willFalg = 7;</code>
     */
    int getWillFalg();

    /**
     * <code>int32 willQos = 8;</code>
     */
    int getWillQos();

    /**
     * <code>int32 willRetain = 9;</code>
     */
    int getWillRetain();
  }
  /**
   * Protobuf type {@code ServerSession}
   */
  public  static final class ServerSession extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerSession)
      ServerSessionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerSession.newBuilder() to construct.
    private ServerSession(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerSession() {
      userId_ = "";
      channelId_ = "";
      sendNoAcks_ = java.util.Collections.emptyList();
      willSends_ = java.util.Collections.emptyList();
      recNoAcks_ = java.util.Collections.emptyList();
      keepLiveSecond_ = 0L;
      willFalg_ = 0;
      willQos_ = 0;
      willRetain_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerSession(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sendNoAcks_ = new java.util.ArrayList<com.yogi.albatross.common.server.MessageProto.Message>();
                mutable_bitField0_ |= 0x00000004;
              }
              sendNoAcks_.add(
                  input.readMessage(com.yogi.albatross.common.server.MessageProto.Message.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                willSends_ = new java.util.ArrayList<com.yogi.albatross.common.server.MessageProto.Message>();
                mutable_bitField0_ |= 0x00000008;
              }
              willSends_.add(
                  input.readMessage(com.yogi.albatross.common.server.MessageProto.Message.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                recNoAcks_ = new java.util.ArrayList<com.yogi.albatross.common.server.MessageProto.Message>();
                mutable_bitField0_ |= 0x00000010;
              }
              recNoAcks_.add(
                  input.readMessage(com.yogi.albatross.common.server.MessageProto.Message.parser(), extensionRegistry));
              break;
            }
            case 48: {

              keepLiveSecond_ = input.readInt64();
              break;
            }
            case 56: {

              willFalg_ = input.readInt32();
              break;
            }
            case 64: {

              willQos_ = input.readInt32();
              break;
            }
            case 72: {

              willRetain_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sendNoAcks_ = java.util.Collections.unmodifiableList(sendNoAcks_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          willSends_ = java.util.Collections.unmodifiableList(willSends_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          recNoAcks_ = java.util.Collections.unmodifiableList(recNoAcks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yogi.albatross.common.server.ServerSessionProto.internal_static_ServerSession_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yogi.albatross.common.server.ServerSessionProto.internal_static_ServerSession_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yogi.albatross.common.server.ServerSessionProto.ServerSession.class, com.yogi.albatross.common.server.ServerSessionProto.ServerSession.Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELID_FIELD_NUMBER = 2;
    private volatile java.lang.Object channelId_;
    /**
     * <code>string channelId = 2;</code>
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>string channelId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDNOACKS_FIELD_NUMBER = 3;
    private java.util.List<com.yogi.albatross.common.server.MessageProto.Message> sendNoAcks_;
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    public java.util.List<com.yogi.albatross.common.server.MessageProto.Message> getSendNoAcksList() {
      return sendNoAcks_;
    }
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    public java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
        getSendNoAcksOrBuilderList() {
      return sendNoAcks_;
    }
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    public int getSendNoAcksCount() {
      return sendNoAcks_.size();
    }
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    public com.yogi.albatross.common.server.MessageProto.Message getSendNoAcks(int index) {
      return sendNoAcks_.get(index);
    }
    /**
     * <code>repeated .Message sendNoAcks = 3;</code>
     */
    public com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getSendNoAcksOrBuilder(
        int index) {
      return sendNoAcks_.get(index);
    }

    public static final int WILLSENDS_FIELD_NUMBER = 4;
    private java.util.List<com.yogi.albatross.common.server.MessageProto.Message> willSends_;
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    public java.util.List<com.yogi.albatross.common.server.MessageProto.Message> getWillSendsList() {
      return willSends_;
    }
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    public java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
        getWillSendsOrBuilderList() {
      return willSends_;
    }
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    public int getWillSendsCount() {
      return willSends_.size();
    }
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    public com.yogi.albatross.common.server.MessageProto.Message getWillSends(int index) {
      return willSends_.get(index);
    }
    /**
     * <code>repeated .Message willSends = 4;</code>
     */
    public com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getWillSendsOrBuilder(
        int index) {
      return willSends_.get(index);
    }

    public static final int RECNOACKS_FIELD_NUMBER = 5;
    private java.util.List<com.yogi.albatross.common.server.MessageProto.Message> recNoAcks_;
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    public java.util.List<com.yogi.albatross.common.server.MessageProto.Message> getRecNoAcksList() {
      return recNoAcks_;
    }
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    public java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
        getRecNoAcksOrBuilderList() {
      return recNoAcks_;
    }
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    public int getRecNoAcksCount() {
      return recNoAcks_.size();
    }
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    public com.yogi.albatross.common.server.MessageProto.Message getRecNoAcks(int index) {
      return recNoAcks_.get(index);
    }
    /**
     * <code>repeated .Message recNoAcks = 5;</code>
     */
    public com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getRecNoAcksOrBuilder(
        int index) {
      return recNoAcks_.get(index);
    }

    public static final int KEEPLIVESECOND_FIELD_NUMBER = 6;
    private long keepLiveSecond_;
    /**
     * <code>int64 keepLiveSecond = 6;</code>
     */
    public long getKeepLiveSecond() {
      return keepLiveSecond_;
    }

    public static final int WILLFALG_FIELD_NUMBER = 7;
    private int willFalg_;
    /**
     * <code>int32 willFalg = 7;</code>
     */
    public int getWillFalg() {
      return willFalg_;
    }

    public static final int WILLQOS_FIELD_NUMBER = 8;
    private int willQos_;
    /**
     * <code>int32 willQos = 8;</code>
     */
    public int getWillQos() {
      return willQos_;
    }

    public static final int WILLRETAIN_FIELD_NUMBER = 9;
    private int willRetain_;
    /**
     * <code>int32 willRetain = 9;</code>
     */
    public int getWillRetain() {
      return willRetain_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, channelId_);
      }
      for (int i = 0; i < sendNoAcks_.size(); i++) {
        output.writeMessage(3, sendNoAcks_.get(i));
      }
      for (int i = 0; i < willSends_.size(); i++) {
        output.writeMessage(4, willSends_.get(i));
      }
      for (int i = 0; i < recNoAcks_.size(); i++) {
        output.writeMessage(5, recNoAcks_.get(i));
      }
      if (keepLiveSecond_ != 0L) {
        output.writeInt64(6, keepLiveSecond_);
      }
      if (willFalg_ != 0) {
        output.writeInt32(7, willFalg_);
      }
      if (willQos_ != 0) {
        output.writeInt32(8, willQos_);
      }
      if (willRetain_ != 0) {
        output.writeInt32(9, willRetain_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, channelId_);
      }
      for (int i = 0; i < sendNoAcks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, sendNoAcks_.get(i));
      }
      for (int i = 0; i < willSends_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, willSends_.get(i));
      }
      for (int i = 0; i < recNoAcks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, recNoAcks_.get(i));
      }
      if (keepLiveSecond_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, keepLiveSecond_);
      }
      if (willFalg_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, willFalg_);
      }
      if (willQos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, willQos_);
      }
      if (willRetain_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, willRetain_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yogi.albatross.common.server.ServerSessionProto.ServerSession)) {
        return super.equals(obj);
      }
      com.yogi.albatross.common.server.ServerSessionProto.ServerSession other = (com.yogi.albatross.common.server.ServerSessionProto.ServerSession) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getChannelId()
          .equals(other.getChannelId());
      result = result && getSendNoAcksList()
          .equals(other.getSendNoAcksList());
      result = result && getWillSendsList()
          .equals(other.getWillSendsList());
      result = result && getRecNoAcksList()
          .equals(other.getRecNoAcksList());
      result = result && (getKeepLiveSecond()
          == other.getKeepLiveSecond());
      result = result && (getWillFalg()
          == other.getWillFalg());
      result = result && (getWillQos()
          == other.getWillQos());
      result = result && (getWillRetain()
          == other.getWillRetain());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      if (getSendNoAcksCount() > 0) {
        hash = (37 * hash) + SENDNOACKS_FIELD_NUMBER;
        hash = (53 * hash) + getSendNoAcksList().hashCode();
      }
      if (getWillSendsCount() > 0) {
        hash = (37 * hash) + WILLSENDS_FIELD_NUMBER;
        hash = (53 * hash) + getWillSendsList().hashCode();
      }
      if (getRecNoAcksCount() > 0) {
        hash = (37 * hash) + RECNOACKS_FIELD_NUMBER;
        hash = (53 * hash) + getRecNoAcksList().hashCode();
      }
      hash = (37 * hash) + KEEPLIVESECOND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKeepLiveSecond());
      hash = (37 * hash) + WILLFALG_FIELD_NUMBER;
      hash = (53 * hash) + getWillFalg();
      hash = (37 * hash) + WILLQOS_FIELD_NUMBER;
      hash = (53 * hash) + getWillQos();
      hash = (37 * hash) + WILLRETAIN_FIELD_NUMBER;
      hash = (53 * hash) + getWillRetain();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yogi.albatross.common.server.ServerSessionProto.ServerSession prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerSession}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerSession)
        com.yogi.albatross.common.server.ServerSessionProto.ServerSessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yogi.albatross.common.server.ServerSessionProto.internal_static_ServerSession_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yogi.albatross.common.server.ServerSessionProto.internal_static_ServerSession_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yogi.albatross.common.server.ServerSessionProto.ServerSession.class, com.yogi.albatross.common.server.ServerSessionProto.ServerSession.Builder.class);
      }

      // Construct using com.yogi.albatross.common.server.ServerSessionProto.ServerSession.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSendNoAcksFieldBuilder();
          getWillSendsFieldBuilder();
          getRecNoAcksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        channelId_ = "";

        if (sendNoAcksBuilder_ == null) {
          sendNoAcks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          sendNoAcksBuilder_.clear();
        }
        if (willSendsBuilder_ == null) {
          willSends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          willSendsBuilder_.clear();
        }
        if (recNoAcksBuilder_ == null) {
          recNoAcks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          recNoAcksBuilder_.clear();
        }
        keepLiveSecond_ = 0L;

        willFalg_ = 0;

        willQos_ = 0;

        willRetain_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yogi.albatross.common.server.ServerSessionProto.internal_static_ServerSession_descriptor;
      }

      @java.lang.Override
      public com.yogi.albatross.common.server.ServerSessionProto.ServerSession getDefaultInstanceForType() {
        return com.yogi.albatross.common.server.ServerSessionProto.ServerSession.getDefaultInstance();
      }

      @java.lang.Override
      public com.yogi.albatross.common.server.ServerSessionProto.ServerSession build() {
        com.yogi.albatross.common.server.ServerSessionProto.ServerSession result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yogi.albatross.common.server.ServerSessionProto.ServerSession buildPartial() {
        com.yogi.albatross.common.server.ServerSessionProto.ServerSession result = new com.yogi.albatross.common.server.ServerSessionProto.ServerSession(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.userId_ = userId_;
        result.channelId_ = channelId_;
        if (sendNoAcksBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            sendNoAcks_ = java.util.Collections.unmodifiableList(sendNoAcks_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.sendNoAcks_ = sendNoAcks_;
        } else {
          result.sendNoAcks_ = sendNoAcksBuilder_.build();
        }
        if (willSendsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            willSends_ = java.util.Collections.unmodifiableList(willSends_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.willSends_ = willSends_;
        } else {
          result.willSends_ = willSendsBuilder_.build();
        }
        if (recNoAcksBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            recNoAcks_ = java.util.Collections.unmodifiableList(recNoAcks_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.recNoAcks_ = recNoAcks_;
        } else {
          result.recNoAcks_ = recNoAcksBuilder_.build();
        }
        result.keepLiveSecond_ = keepLiveSecond_;
        result.willFalg_ = willFalg_;
        result.willQos_ = willQos_;
        result.willRetain_ = willRetain_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yogi.albatross.common.server.ServerSessionProto.ServerSession) {
          return mergeFrom((com.yogi.albatross.common.server.ServerSessionProto.ServerSession)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yogi.albatross.common.server.ServerSessionProto.ServerSession other) {
        if (other == com.yogi.albatross.common.server.ServerSessionProto.ServerSession.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (sendNoAcksBuilder_ == null) {
          if (!other.sendNoAcks_.isEmpty()) {
            if (sendNoAcks_.isEmpty()) {
              sendNoAcks_ = other.sendNoAcks_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSendNoAcksIsMutable();
              sendNoAcks_.addAll(other.sendNoAcks_);
            }
            onChanged();
          }
        } else {
          if (!other.sendNoAcks_.isEmpty()) {
            if (sendNoAcksBuilder_.isEmpty()) {
              sendNoAcksBuilder_.dispose();
              sendNoAcksBuilder_ = null;
              sendNoAcks_ = other.sendNoAcks_;
              bitField0_ = (bitField0_ & ~0x00000004);
              sendNoAcksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSendNoAcksFieldBuilder() : null;
            } else {
              sendNoAcksBuilder_.addAllMessages(other.sendNoAcks_);
            }
          }
        }
        if (willSendsBuilder_ == null) {
          if (!other.willSends_.isEmpty()) {
            if (willSends_.isEmpty()) {
              willSends_ = other.willSends_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureWillSendsIsMutable();
              willSends_.addAll(other.willSends_);
            }
            onChanged();
          }
        } else {
          if (!other.willSends_.isEmpty()) {
            if (willSendsBuilder_.isEmpty()) {
              willSendsBuilder_.dispose();
              willSendsBuilder_ = null;
              willSends_ = other.willSends_;
              bitField0_ = (bitField0_ & ~0x00000008);
              willSendsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWillSendsFieldBuilder() : null;
            } else {
              willSendsBuilder_.addAllMessages(other.willSends_);
            }
          }
        }
        if (recNoAcksBuilder_ == null) {
          if (!other.recNoAcks_.isEmpty()) {
            if (recNoAcks_.isEmpty()) {
              recNoAcks_ = other.recNoAcks_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureRecNoAcksIsMutable();
              recNoAcks_.addAll(other.recNoAcks_);
            }
            onChanged();
          }
        } else {
          if (!other.recNoAcks_.isEmpty()) {
            if (recNoAcksBuilder_.isEmpty()) {
              recNoAcksBuilder_.dispose();
              recNoAcksBuilder_ = null;
              recNoAcks_ = other.recNoAcks_;
              bitField0_ = (bitField0_ & ~0x00000010);
              recNoAcksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecNoAcksFieldBuilder() : null;
            } else {
              recNoAcksBuilder_.addAllMessages(other.recNoAcks_);
            }
          }
        }
        if (other.getKeepLiveSecond() != 0L) {
          setKeepLiveSecond(other.getKeepLiveSecond());
        }
        if (other.getWillFalg() != 0) {
          setWillFalg(other.getWillFalg());
        }
        if (other.getWillQos() != 0) {
          setWillQos(other.getWillQos());
        }
        if (other.getWillRetain() != 0) {
          setWillRetain(other.getWillRetain());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yogi.albatross.common.server.ServerSessionProto.ServerSession parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yogi.albatross.common.server.ServerSessionProto.ServerSession) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object channelId_ = "";
      /**
       * <code>string channelId = 2;</code>
       */
      public java.lang.String getChannelId() {
        java.lang.Object ref = channelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string channelId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        java.lang.Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channelId = 2;</code>
       */
      public Builder setChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 2;</code>
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 2;</code>
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.yogi.albatross.common.server.MessageProto.Message> sendNoAcks_ =
        java.util.Collections.emptyList();
      private void ensureSendNoAcksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sendNoAcks_ = new java.util.ArrayList<com.yogi.albatross.common.server.MessageProto.Message>(sendNoAcks_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> sendNoAcksBuilder_;

      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public java.util.List<com.yogi.albatross.common.server.MessageProto.Message> getSendNoAcksList() {
        if (sendNoAcksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sendNoAcks_);
        } else {
          return sendNoAcksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public int getSendNoAcksCount() {
        if (sendNoAcksBuilder_ == null) {
          return sendNoAcks_.size();
        } else {
          return sendNoAcksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message getSendNoAcks(int index) {
        if (sendNoAcksBuilder_ == null) {
          return sendNoAcks_.get(index);
        } else {
          return sendNoAcksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder setSendNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message value) {
        if (sendNoAcksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendNoAcksIsMutable();
          sendNoAcks_.set(index, value);
          onChanged();
        } else {
          sendNoAcksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder setSendNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (sendNoAcksBuilder_ == null) {
          ensureSendNoAcksIsMutable();
          sendNoAcks_.set(index, builderForValue.build());
          onChanged();
        } else {
          sendNoAcksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder addSendNoAcks(com.yogi.albatross.common.server.MessageProto.Message value) {
        if (sendNoAcksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendNoAcksIsMutable();
          sendNoAcks_.add(value);
          onChanged();
        } else {
          sendNoAcksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder addSendNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message value) {
        if (sendNoAcksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendNoAcksIsMutable();
          sendNoAcks_.add(index, value);
          onChanged();
        } else {
          sendNoAcksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder addSendNoAcks(
          com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (sendNoAcksBuilder_ == null) {
          ensureSendNoAcksIsMutable();
          sendNoAcks_.add(builderForValue.build());
          onChanged();
        } else {
          sendNoAcksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder addSendNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (sendNoAcksBuilder_ == null) {
          ensureSendNoAcksIsMutable();
          sendNoAcks_.add(index, builderForValue.build());
          onChanged();
        } else {
          sendNoAcksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder addAllSendNoAcks(
          java.lang.Iterable<? extends com.yogi.albatross.common.server.MessageProto.Message> values) {
        if (sendNoAcksBuilder_ == null) {
          ensureSendNoAcksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sendNoAcks_);
          onChanged();
        } else {
          sendNoAcksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder clearSendNoAcks() {
        if (sendNoAcksBuilder_ == null) {
          sendNoAcks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          sendNoAcksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public Builder removeSendNoAcks(int index) {
        if (sendNoAcksBuilder_ == null) {
          ensureSendNoAcksIsMutable();
          sendNoAcks_.remove(index);
          onChanged();
        } else {
          sendNoAcksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder getSendNoAcksBuilder(
          int index) {
        return getSendNoAcksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getSendNoAcksOrBuilder(
          int index) {
        if (sendNoAcksBuilder_ == null) {
          return sendNoAcks_.get(index);  } else {
          return sendNoAcksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
           getSendNoAcksOrBuilderList() {
        if (sendNoAcksBuilder_ != null) {
          return sendNoAcksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sendNoAcks_);
        }
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder addSendNoAcksBuilder() {
        return getSendNoAcksFieldBuilder().addBuilder(
            com.yogi.albatross.common.server.MessageProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder addSendNoAcksBuilder(
          int index) {
        return getSendNoAcksFieldBuilder().addBuilder(
            index, com.yogi.albatross.common.server.MessageProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message sendNoAcks = 3;</code>
       */
      public java.util.List<com.yogi.albatross.common.server.MessageProto.Message.Builder> 
           getSendNoAcksBuilderList() {
        return getSendNoAcksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
          getSendNoAcksFieldBuilder() {
        if (sendNoAcksBuilder_ == null) {
          sendNoAcksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder>(
                  sendNoAcks_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          sendNoAcks_ = null;
        }
        return sendNoAcksBuilder_;
      }

      private java.util.List<com.yogi.albatross.common.server.MessageProto.Message> willSends_ =
        java.util.Collections.emptyList();
      private void ensureWillSendsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          willSends_ = new java.util.ArrayList<com.yogi.albatross.common.server.MessageProto.Message>(willSends_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> willSendsBuilder_;

      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public java.util.List<com.yogi.albatross.common.server.MessageProto.Message> getWillSendsList() {
        if (willSendsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(willSends_);
        } else {
          return willSendsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public int getWillSendsCount() {
        if (willSendsBuilder_ == null) {
          return willSends_.size();
        } else {
          return willSendsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message getWillSends(int index) {
        if (willSendsBuilder_ == null) {
          return willSends_.get(index);
        } else {
          return willSendsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder setWillSends(
          int index, com.yogi.albatross.common.server.MessageProto.Message value) {
        if (willSendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWillSendsIsMutable();
          willSends_.set(index, value);
          onChanged();
        } else {
          willSendsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder setWillSends(
          int index, com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (willSendsBuilder_ == null) {
          ensureWillSendsIsMutable();
          willSends_.set(index, builderForValue.build());
          onChanged();
        } else {
          willSendsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder addWillSends(com.yogi.albatross.common.server.MessageProto.Message value) {
        if (willSendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWillSendsIsMutable();
          willSends_.add(value);
          onChanged();
        } else {
          willSendsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder addWillSends(
          int index, com.yogi.albatross.common.server.MessageProto.Message value) {
        if (willSendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWillSendsIsMutable();
          willSends_.add(index, value);
          onChanged();
        } else {
          willSendsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder addWillSends(
          com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (willSendsBuilder_ == null) {
          ensureWillSendsIsMutable();
          willSends_.add(builderForValue.build());
          onChanged();
        } else {
          willSendsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder addWillSends(
          int index, com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (willSendsBuilder_ == null) {
          ensureWillSendsIsMutable();
          willSends_.add(index, builderForValue.build());
          onChanged();
        } else {
          willSendsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder addAllWillSends(
          java.lang.Iterable<? extends com.yogi.albatross.common.server.MessageProto.Message> values) {
        if (willSendsBuilder_ == null) {
          ensureWillSendsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, willSends_);
          onChanged();
        } else {
          willSendsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder clearWillSends() {
        if (willSendsBuilder_ == null) {
          willSends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          willSendsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public Builder removeWillSends(int index) {
        if (willSendsBuilder_ == null) {
          ensureWillSendsIsMutable();
          willSends_.remove(index);
          onChanged();
        } else {
          willSendsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder getWillSendsBuilder(
          int index) {
        return getWillSendsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getWillSendsOrBuilder(
          int index) {
        if (willSendsBuilder_ == null) {
          return willSends_.get(index);  } else {
          return willSendsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
           getWillSendsOrBuilderList() {
        if (willSendsBuilder_ != null) {
          return willSendsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(willSends_);
        }
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder addWillSendsBuilder() {
        return getWillSendsFieldBuilder().addBuilder(
            com.yogi.albatross.common.server.MessageProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder addWillSendsBuilder(
          int index) {
        return getWillSendsFieldBuilder().addBuilder(
            index, com.yogi.albatross.common.server.MessageProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message willSends = 4;</code>
       */
      public java.util.List<com.yogi.albatross.common.server.MessageProto.Message.Builder> 
           getWillSendsBuilderList() {
        return getWillSendsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
          getWillSendsFieldBuilder() {
        if (willSendsBuilder_ == null) {
          willSendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder>(
                  willSends_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          willSends_ = null;
        }
        return willSendsBuilder_;
      }

      private java.util.List<com.yogi.albatross.common.server.MessageProto.Message> recNoAcks_ =
        java.util.Collections.emptyList();
      private void ensureRecNoAcksIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          recNoAcks_ = new java.util.ArrayList<com.yogi.albatross.common.server.MessageProto.Message>(recNoAcks_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> recNoAcksBuilder_;

      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public java.util.List<com.yogi.albatross.common.server.MessageProto.Message> getRecNoAcksList() {
        if (recNoAcksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recNoAcks_);
        } else {
          return recNoAcksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public int getRecNoAcksCount() {
        if (recNoAcksBuilder_ == null) {
          return recNoAcks_.size();
        } else {
          return recNoAcksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message getRecNoAcks(int index) {
        if (recNoAcksBuilder_ == null) {
          return recNoAcks_.get(index);
        } else {
          return recNoAcksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder setRecNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message value) {
        if (recNoAcksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecNoAcksIsMutable();
          recNoAcks_.set(index, value);
          onChanged();
        } else {
          recNoAcksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder setRecNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (recNoAcksBuilder_ == null) {
          ensureRecNoAcksIsMutable();
          recNoAcks_.set(index, builderForValue.build());
          onChanged();
        } else {
          recNoAcksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder addRecNoAcks(com.yogi.albatross.common.server.MessageProto.Message value) {
        if (recNoAcksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecNoAcksIsMutable();
          recNoAcks_.add(value);
          onChanged();
        } else {
          recNoAcksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder addRecNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message value) {
        if (recNoAcksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecNoAcksIsMutable();
          recNoAcks_.add(index, value);
          onChanged();
        } else {
          recNoAcksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder addRecNoAcks(
          com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (recNoAcksBuilder_ == null) {
          ensureRecNoAcksIsMutable();
          recNoAcks_.add(builderForValue.build());
          onChanged();
        } else {
          recNoAcksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder addRecNoAcks(
          int index, com.yogi.albatross.common.server.MessageProto.Message.Builder builderForValue) {
        if (recNoAcksBuilder_ == null) {
          ensureRecNoAcksIsMutable();
          recNoAcks_.add(index, builderForValue.build());
          onChanged();
        } else {
          recNoAcksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder addAllRecNoAcks(
          java.lang.Iterable<? extends com.yogi.albatross.common.server.MessageProto.Message> values) {
        if (recNoAcksBuilder_ == null) {
          ensureRecNoAcksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, recNoAcks_);
          onChanged();
        } else {
          recNoAcksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder clearRecNoAcks() {
        if (recNoAcksBuilder_ == null) {
          recNoAcks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          recNoAcksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public Builder removeRecNoAcks(int index) {
        if (recNoAcksBuilder_ == null) {
          ensureRecNoAcksIsMutable();
          recNoAcks_.remove(index);
          onChanged();
        } else {
          recNoAcksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder getRecNoAcksBuilder(
          int index) {
        return getRecNoAcksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.MessageOrBuilder getRecNoAcksOrBuilder(
          int index) {
        if (recNoAcksBuilder_ == null) {
          return recNoAcks_.get(index);  } else {
          return recNoAcksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public java.util.List<? extends com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
           getRecNoAcksOrBuilderList() {
        if (recNoAcksBuilder_ != null) {
          return recNoAcksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recNoAcks_);
        }
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder addRecNoAcksBuilder() {
        return getRecNoAcksFieldBuilder().addBuilder(
            com.yogi.albatross.common.server.MessageProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public com.yogi.albatross.common.server.MessageProto.Message.Builder addRecNoAcksBuilder(
          int index) {
        return getRecNoAcksFieldBuilder().addBuilder(
            index, com.yogi.albatross.common.server.MessageProto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .Message recNoAcks = 5;</code>
       */
      public java.util.List<com.yogi.albatross.common.server.MessageProto.Message.Builder> 
           getRecNoAcksBuilderList() {
        return getRecNoAcksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder> 
          getRecNoAcksFieldBuilder() {
        if (recNoAcksBuilder_ == null) {
          recNoAcksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yogi.albatross.common.server.MessageProto.Message, com.yogi.albatross.common.server.MessageProto.Message.Builder, com.yogi.albatross.common.server.MessageProto.MessageOrBuilder>(
                  recNoAcks_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          recNoAcks_ = null;
        }
        return recNoAcksBuilder_;
      }

      private long keepLiveSecond_ ;
      /**
       * <code>int64 keepLiveSecond = 6;</code>
       */
      public long getKeepLiveSecond() {
        return keepLiveSecond_;
      }
      /**
       * <code>int64 keepLiveSecond = 6;</code>
       */
      public Builder setKeepLiveSecond(long value) {
        
        keepLiveSecond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 keepLiveSecond = 6;</code>
       */
      public Builder clearKeepLiveSecond() {
        
        keepLiveSecond_ = 0L;
        onChanged();
        return this;
      }

      private int willFalg_ ;
      /**
       * <code>int32 willFalg = 7;</code>
       */
      public int getWillFalg() {
        return willFalg_;
      }
      /**
       * <code>int32 willFalg = 7;</code>
       */
      public Builder setWillFalg(int value) {
        
        willFalg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 willFalg = 7;</code>
       */
      public Builder clearWillFalg() {
        
        willFalg_ = 0;
        onChanged();
        return this;
      }

      private int willQos_ ;
      /**
       * <code>int32 willQos = 8;</code>
       */
      public int getWillQos() {
        return willQos_;
      }
      /**
       * <code>int32 willQos = 8;</code>
       */
      public Builder setWillQos(int value) {
        
        willQos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 willQos = 8;</code>
       */
      public Builder clearWillQos() {
        
        willQos_ = 0;
        onChanged();
        return this;
      }

      private int willRetain_ ;
      /**
       * <code>int32 willRetain = 9;</code>
       */
      public int getWillRetain() {
        return willRetain_;
      }
      /**
       * <code>int32 willRetain = 9;</code>
       */
      public Builder setWillRetain(int value) {
        
        willRetain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 willRetain = 9;</code>
       */
      public Builder clearWillRetain() {
        
        willRetain_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerSession)
    }

    // @@protoc_insertion_point(class_scope:ServerSession)
    private static final com.yogi.albatross.common.server.ServerSessionProto.ServerSession DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yogi.albatross.common.server.ServerSessionProto.ServerSession();
    }

    public static com.yogi.albatross.common.server.ServerSessionProto.ServerSession getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerSession>
        PARSER = new com.google.protobuf.AbstractParser<ServerSession>() {
      @java.lang.Override
      public ServerSession parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerSession(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerSession> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerSession> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yogi.albatross.common.server.ServerSessionProto.ServerSession getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerSession_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerSession_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024server_session.proto\032\rmessage.proto\"\331\001" +
      "\n\rServerSession\022\016\n\006userId\030\001 \001(\t\022\021\n\tchann" +
      "elId\030\002 \001(\t\022\034\n\nsendNoAcks\030\003 \003(\0132\010.Message" +
      "\022\033\n\twillSends\030\004 \003(\0132\010.Message\022\033\n\trecNoAc" +
      "ks\030\005 \003(\0132\010.Message\022\026\n\016keepLiveSecond\030\006 \001" +
      "(\003\022\020\n\010willFalg\030\007 \001(\005\022\017\n\007willQos\030\010 \001(\005\022\022\n" +
      "\nwillRetain\030\t \001(\005B6\n com.yogi.albatross." +
      "common.serverB\022ServerSessionProtob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yogi.albatross.common.server.MessageProto.getDescriptor(),
        }, assigner);
    internal_static_ServerSession_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerSession_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerSession_descriptor,
        new java.lang.String[] { "UserId", "ChannelId", "SendNoAcks", "WillSends", "RecNoAcks", "KeepLiveSecond", "WillFalg", "WillQos", "WillRetain", });
    com.yogi.albatross.common.server.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
